[build]
builder = "NIXPACKS"
buildCommand = "python && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate core 0018_casetimelineevent_followuptask_notification --fake && python backend/manage.py migrate"

[deploy]
startCommand = "gunicorn lims_project.wsgi:application --chdir backend"
