# Generated by Django 5.2.7 on 2026-01-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
