# Generated by Django 5.2.7 on 2026-01-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_labreport_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.sample'),
        ),
    ]
