# Generated by Django 5.2.7 on 2026-01-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_labreport_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='report_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
