# Generated by Django 5.2.7 on 2026-01-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_labreport_report_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='created_at',
            new_name='collection_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(default='collected', max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='test_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.labtestorder'),
        ),
    ]
