# Generated by Django 5.2.7 on 2026-01-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_created_at_sample_collection_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='test_order',
        ),
    ]
