# Generated by Django 5.2.7 on 2026-01-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sample_test_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='core.patientprofile'),
            preserve_default=False,
        ),
    ]
