# Generated by Django 5.2.7 on 2026-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_labreport_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientlink',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientlink',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientlink',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
