# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_0018_conflicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
